# Generated by Django 4.0.4 on 2022-05-04 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 13, 56, 58, 898282, tzinfo=utc), verbose_name='date de creation'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
