# Generated by Django 4.0.4 on 2022-05-04 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_date_create_user_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de creation'),
        ),
    ]
